//go:build linux

package shim

import (
	"errors"
	"os"
	"path/filepath"
	"testing"

	"golang.org/x/sys/unix"
)

// TestDNSMountSourceUsesExactPrivateRegularInode verifies the temporary DNS
// source is mountable filesystem state, contains canonical bytes, and is
// removed only through its retained owner-directory identity.
func TestDNSMountSourceUsesExactPrivateRegularInode(t *testing.T) {
	directoryPath := t.TempDir()
	directoryFD, err := unix.Open(directoryPath, unix.O_RDONLY|unix.O_DIRECTORY|unix.O_NOFOLLOW|unix.O_CLOEXEC, 0)
	if err != nil {
		t.Fatal(err)
	}
	defer unix.Close(directoryFD)
	dnsFD, err := createDNSMountSource(directoryFD, []string{"1.1.1.1", "2001:4860:4860::8888"})
	if err != nil {
		t.Fatal(err)
	}
	defer unix.Close(dnsFD)
	path := filepath.Join(directoryPath, dnsMountSourceName)
	info, err := os.Lstat(path)
	if err != nil {
		t.Fatal(err)
	}
	if !info.Mode().IsRegular() || info.Mode().Perm() != 0o600 {
		t.Fatalf("DNS mount source mode = %v, want private regular file", info.Mode())
	}
	payload, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# generated by mydocker\nnameserver 1.1.1.1\nnameserver 2001:4860:4860::8888\n"
	if string(payload) != want {
		t.Fatalf("DNS mount source = %q, want %q", payload, want)
	}
	if err := removeDNSMountSource(directoryFD, dnsFD); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Lstat(path); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("DNS mount source survived cleanup: %v", err)
	}
}

// TestDNSMountSourceRefusesReplacementCleanup verifies a path swap cannot make
// cleanup unlink another inode even though the original descriptor remains open.
func TestDNSMountSourceRefusesReplacementCleanup(t *testing.T) {
	directoryPath := t.TempDir()
	directoryFD, err := unix.Open(directoryPath, unix.O_RDONLY|unix.O_DIRECTORY|unix.O_NOFOLLOW|unix.O_CLOEXEC, 0)
	if err != nil {
		t.Fatal(err)
	}
	defer unix.Close(directoryFD)
	dnsFD, err := createDNSMountSource(directoryFD, nil)
	if err != nil {
		t.Fatal(err)
	}
	defer unix.Close(dnsFD)
	path := filepath.Join(directoryPath, dnsMountSourceName)
	moved := filepath.Join(directoryPath, "original-source")
	if err := os.Rename(path, moved); err != nil {
		t.Fatal(err)
	}
	replacement := []byte("replacement")
	if err := os.WriteFile(path, replacement, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := removeDNSMountSource(directoryFD, dnsFD); err == nil {
		t.Fatal("replacement path was accepted for exact cleanup")
	}
	if payload, err := os.ReadFile(path); err != nil || string(payload) != string(replacement) {
		t.Fatalf("replacement was changed: payload=%q error=%v", payload, err)
	}
}
