//go:build linux

package shim

import (
	"context"
	"errors"
	"fmt"
	"strings"

	"golang.org/x/sys/unix"

	"mydocker/internal/isolation"
)

// PID1RootfsPreparer executes the deferred pivot in the long-lived init
// wrapper and injects DNS from an anonymous descriptor rather than a host path.
type PID1RootfsPreparer struct {
	ops isolation.Ops
}

// NewPID1RootfsPreparer constructs the production Linux preparer without
// mounting or changing namespaces; those effects occur only on PrepareRootfs.
func NewPID1RootfsPreparer() *PID1RootfsPreparer {
	return &PID1RootfsPreparer{ops: isolation.NewSystemOps()}
}

// PrepareRootfs creates a private resolv.conf memfd, verifies this process is
// the expected PID1/mount owner, then performs the one-shot bind and pivot sequence.
func (preparer *PID1RootfsPreparer) PrepareRootfs(request RootfsRequest) (resultErr error) {
	if preparer == nil || preparer.ops == nil {
		return errors.New("PID1 rootfs preparer is not configured")
	}
	if err := request.Validate(); err != nil {
		return err
	}
	dnsFD, err := createDNSMemfd(request.DNS)
	if err != nil {
		return err
	}
	defer func() {
		resultErr = errors.Join(resultErr, unix.Close(dnsFD))
	}()
	bootstrap := isolation.PID1Bootstrap{
		SchemaVersion: isolation.PID1BootstrapSchemaVersion,
		Namespaces: isolation.CreatedNamespaceSet{Inodes: map[isolation.NamespaceType]uint64{
			isolation.NamespacePID: request.PIDNamespaceInode, isolation.NamespaceMount: request.MountNamespaceInode,
		}},
		Rootfs: request.Source,
	}
	return isolation.RunPID1Child(context.Background(), preparer.ops, bootstrap, func(ctx context.Context, helper *isolation.LockedHelper) error {
		return helper.PrepareRootWithDNS(ctx, request.Source, dnsFD)
	})
}

// createDNSMemfd publishes only canonical nameserver lines into a sealed
// close-on-exec anonymous file suitable for a fixed bind mount.
func createDNSMemfd(servers []string) (int, error) {
	payload := renderResolvConf(servers)
	fd, err := unix.MemfdCreate("mydocker-resolv-conf", unix.MFD_CLOEXEC|unix.MFD_ALLOW_SEALING)
	if err != nil {
		return -1, fmt.Errorf("create resolv.conf memfd: %w", err)
	}
	succeeded := false
	defer func() {
		if !succeeded {
			_ = unix.Close(fd)
		}
	}()
	for len(payload) > 0 {
		written, writeErr := unix.Write(fd, payload)
		if writeErr != nil {
			return -1, fmt.Errorf("write resolv.conf memfd: %w", writeErr)
		}
		if written <= 0 || written > len(payload) {
			return -1, errors.New("write resolv.conf memfd made no progress")
		}
		payload = payload[written:]
	}
	if err := unix.Fsync(fd); err != nil {
		return -1, fmt.Errorf("synchronize resolv.conf memfd: %w", err)
	}
	seals := unix.F_SEAL_WRITE | unix.F_SEAL_GROW | unix.F_SEAL_SHRINK | unix.F_SEAL_SEAL
	if _, err := unix.FcntlInt(uintptr(fd), unix.F_ADD_SEALS, seals); err != nil {
		return -1, fmt.Errorf("seal resolv.conf memfd: %w", err)
	}
	succeeded = true
	return fd, nil
}

// renderResolvConf returns deterministic bytes for the ordered Sandbox DNS
// contract, including an intentionally empty managed file for network=none.
func renderResolvConf(servers []string) []byte {
	var builder strings.Builder
	builder.WriteString("# generated by mydocker\n")
	for _, server := range servers {
		builder.WriteString("nameserver ")
		builder.WriteString(server)
		builder.WriteByte('\n')
	}
	return []byte(builder.String())
}
